name: pnpm-verify
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-version:
        type: string
        required: false
        default: '[18, 20, 22]'
      pnpm-version:
        type: string
        required: false
      skip-codecov:
        type: boolean
        required: false
        default: false
jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        node-version: ${{ fromJson(inputs.node-version) }}
    steps:
      - name: "Start X Virtual Frame Buffer"
        run: "echo \"DISPLAY=:99.0\" >> $GITHUB_ENV && Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &"

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install playwright browsers
        run: pnpx playwright install --with-deps chromium

      - name: Install Dependencies
        run: pnpm install

      - name: Verify
        run: pnpm verify

      - name: codecov
        if: inputs.skip-codecov == false && matrix.os == 'ubuntu-latest' && matrix.node-version == 18
        uses: codecov/codecov-action@v5
