name: pnpm-verify
on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node-version:
        type: string
        required: false
        default: '[18, 20, 22]'
      pnpm-version:
        type: string
        required: false
      skip-codecov:
        type: boolean
        required: false
        default: false
jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ${{ fromJson(inputs.os) }}
        node-version: ${{ fromJson(inputs.node-version) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: ${{ inputs.pnpm-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Verify
        run: pnpm verify

      - name: codecov
        if: inputs.skip-codecov == false && matrix.os == 'ubuntu-latest' && matrix.node-version == 18
        uses: codecov/codecov-action@v5
